name: BadgeSort
description: Generate and sort branded Shields.io and Badgen.net badges by color
branding:
  icon: book-open
  color: green
inputs:
  opts:
    description: Additional options
    required: false
  slugs:
    description: SimpleIcons.org slugs to use
    required: false
  format:
    description: Output format
    required: false
    default: 'markdown'
  id:
    description: 'Badge generation ID - must match the ID in comment markers: <!-- start chipwolf/badgesort {id} --> and <!-- end chipwolf/badgesort {id} -->'
    required: false
    default: default
  provider:
    description: Badge provider (shields/badgen)
    required: false
    default: shields
  sort:
    description: Color sorting algorithm
    required: false
    default: hilbert
  style:
    description: Shields.io badge style
    required: false
    default: for-the-badge
  thanks:
    description: Show the BadgeSort badge
    required: false
    default: true
    type: boolean
  random:
    description: Number of random icons to generate
    required: false
    default: 0
  verify:
    description: Verify the generated badge is valid by requesting it from the badge provider
    required: false
    default: false
    type: boolean
  output:
    description: 'Output file name - requires comment markers in the target file: <!-- start chipwolf/badgesort {id} --> and <!-- end chipwolf/badgesort {id} -->. Without markers, outputs to stdout.'
    required: false
  embed-svg:
    description: Always embed SVG data URIs in Shields.io badges instead of using logo slugs
    required: false
    default: 'false'
  skip-logo-check:
    description: Skip checking if logos are missing from Shields.io (faster but may result in badges without icons)
    required: false
    default: 'false'
runs:
  using: docker
  image: Dockerfile

outputs:
  badges:
    description: Generated badges markup when no output file is provided
