name: 'generate-badges'
description: 'Generate and sort branded Shields.io badges by color'
branding:
  icon: 'book-open'
  color: 'green'
inputs:
  opts:
    description: 'Additional options'
    required: false
    default: ''
  slugs:
    description: 'SimpleIcons.org slugs to use.'
    required: false
    default: ''
  format:
    description: 'Output format.'
    required: false
    default: 'markdown'
  id:
    description: 'Badge generation ID.'
    required: false
    default: 'default'
  sort:
    description: 'Color sorting algorithm'
    required: false
    default: 'hilbert'
  style:
    description: 'Shields.io badge style.'
    required: false
    default: 'for-the-badge'
  thanks:
    description: 'Show the BadgeSort badge.'
    required: false
    default: true
    type: boolean
  random:
    description: 'Number of random icons to generate.'
    required: false
    default: 1
  verify:
    description: 'Verify the generated badge is valid by requesting it from Shields.io.'
    required: false
    default: false
    type: boolean
  output:
    description: 'Output file name'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
