name: BadgeSort
description: Generate and sort branded Shields.io badges by color
branding:
  icon: book-open
  color: green
inputs:
  opts:
    description: Additional options
    required: false
  slugs:
    description: SimpleIcons.org slugs to use
    required: false
  format:
    description: Output format
    required: false
    default: 'markdown'
  id:
    description: Badge generation ID
    required: false
    default: default
  sort:
    description: Color sorting algorithm
    required: false
    default: hilbert
  style:
    description: Shields.io badge style
    required: false
    default: for-the-badge
  thanks:
    description: Show the BadgeSort badge
    required: false
    default: true
    type: boolean
  random:
    description: Number of random icons to generate
    required: false
    default: 0
  verify:
    description: Verify the generated badge is valid by requesting it from Shields.io
    required: false
    default: false
    type: boolean
  output:
    description: Output file name
    required: false
runs:
  using: docker
  image: Dockerfile

outputs:
  badges:
    description: Generated badges markup when no output file is provided
