---
name: Image

on:
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "chipwolf/generate-badges"

jobs:
  build:
    name: Build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and cache Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'latest' }}"
        cache-from: type=gha
        cache-to: type=gha,mode=max
