---
name: Image

"on":
  push:
    branches:
      - main
    tags:
      - '*'

permissions: write-all

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: chipwolf/badgesort

jobs:
  build:
    name: Build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      with:
        fetch-depth: 1
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@f211e3e9ded2d9377c8cadc4489a4e38014bc4c9 # v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and cache Docker image
      uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v4
      with:
        context: .
        push: true
        tags: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'latest' }}"
        cache-from: type=gha
        cache-to: type=gha,mode=max
  badgesort:
    if: startsWith(github.ref, 'refs/tags/')
    name: Run BadgeSort
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: docker://ghcr.io/chipwolf/badgesort:latest
        with:
          format: markdown
          id: default
          output: README.md
          slugs: |
            osu
            github
            americanexpress
            nodered
            opensea
          sort: hilbert
          style: for-the-badge
      - uses: docker://ghcr.io/chipwolf/badgesort:latest
        with:
          format: html
          id: foobar
          output: README.md
          random: 5
          sort: 'false'
          style: flat-square
      - uses: docker://ghcr.io/chipwolf/badgesort:latest
        with:
          opts: --hue-rotate 240
          id: example
          format: html
          output: README.md
          sort: step_invert
          style: flat
          slugs: |
            angular,apollographql,brave,d3dotjs,docker
            git,githubactions,googlecloud,graphql,heroku
            html5,insomnia,mongodb,nestjs,nodedotjs
            npm,prettier,react,reactivex,redux
            rollupdotjs,sass,styledcomponents,typescript,webpack
      - uses: EndBug/add-and-commit@1bad3abcf0d6ec49a5857d124b0bfb52dc7bb081 # v9
        with:
          default_author: github_actions
          message: 'chore(docs): refresh badgesort'
