---
name: Image

"on":
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - '**.md'

permissions: write-all

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: chipwolf/badgesort

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      with:
        fetch-depth: 1
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and cache Docker image
      uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5
      with:
        context: .
        push: ${{ github.event_name == 'push' }}
        tags: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'latest' }}"
        cache-from: type=gha
        cache-to: type=gha,mode=max
  badgesort:
    if: startsWith(github.ref, 'refs/tags/') || github.event_name != 'push'
    name: Run BadgeSort
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: docker://ghcr.io/chipwolf/badgesort:latest
        with:
          format: markdown
          id: default
          output: README.md
          slugs: |
            osu
            github
            americanexpress
            nodered
            opensea
          sort: hilbert
          style: for-the-badge
      - uses: docker://ghcr.io/chipwolf/badgesort:latest
        with:
          format: html
          id: foobar
          output: README.md
          random: 5
          sort: 'false'
          style: flat-square
      - uses: docker://ghcr.io/chipwolf/badgesort:latest
        with:
          opts: --hue-rotate 240
          id: example
          format: html
          output: README.md
          sort: step_invert
          style: flat
          slugs: |
            angular,apollographql,brave,d3dotjs,docker
            git,githubactions,googlecloud,graphql,heroku
            html5,insomnia,mongodb,nestjs,nodedotjs
            npm,prettier,react,reactivex,redux
            rollupdotjs,sass,styledcomponents,typescript,webpack
      - uses: EndBug/add-and-commit@1bad3abcf0d6ec49a5857d124b0bfb52dc7bb081 # v9
        with:
          default_author: github_actions
          message: 'chore(docs): refresh badgesort'
