---
name: Badges

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/generate-badges.yaml

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker://ghcr.io/chipwolf/generate-badges:latest
        with:
          format: markdown
          id: default
          output: README.md
          slugs: |
            osu
            github
            americanexpress
            nodered
            opensea
          sort: 'hilbert'
          style: 'for-the-badge'
      - uses: docker://ghcr.io/chipwolf/generate-badges:latest
        with:
          format: html
          id: foobar
          output: README.md
          random: 5
          sort: 'false'
          style: flat-square
      - uses: docker://ghcr.io/chipwolf/generate-badges:latest
        with:
          opts: '--hue-rotate 240'
          id: example
          format: html
          output: README.md
          sort: 'step_invert'
          style: flat
          slugs: |
            angular,apollographql,brave,d3dotjs,docker
            git,githubactions,googlecloud,graphql,heroku
            html5,insomnia,mongodb,nestjs,nodedotjs
            npm,prettier,react,reactivex,redux
            rollupdotjs,sass,styledcomponents,typescript,webpack
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
