---
name: Render All Badges

"on":
  workflow_dispatch:

permissions: write-all

jobs:
  badgesort:
    name: Run BadgeSort
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 1
      - name: All Badges
        uses: ./
        with:
          output: BADGES.md
          random: -1
      - name: Commit and push
        uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10
        with:
          default_author: github_actions
          message: 'chore(docs): refresh badgesort'
